# Workflow para deploy de um site Bolt.DIY para GitHub Pages
name: Deploy Bolt.DIY Site to GitHub Pages

on:
  # Ativar em push para a branch principal
  push:
    branches: ["main"]
  
  # Permitir execução manual da Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de deploy direto (sem build)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Configurar páginas
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Criar arquivo .nojekyll para evitar processamento Jekyll
      - name: Create .nojekyll file
        run: touch .nojekyll

      # Upload do site como artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload todo o diretório raiz
          path: '.'

      # Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
