# Workflow for building and deploying a Bolt.DIY site to GitHub Pages
name: Deploy Site with GitHub Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a more stable version

      # Debug: List directories
      - name: List directories before build
        run: ls -la
        
      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          # Check if package.json exists
          if [ -f "package.json" ]; then
            npm install
            npm run build
          else
            echo "No package.json found, skipping npm build"
          fi
          
      # Debug: List directories after build
      - name: List directories after build
        run: |
          echo "Current directory:"
          ls -la
          echo "Looking for build outputs:"
          find . -type d -name "dist" -o -name "build" -o -name "public"
      
      # Create an empty .nojekyll file
      - name: Add .nojekyll file
        run: touch .nojekyll
      
      # Upload the built files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Try to find the correct output directory
          path: '.'  # Upload everything for now, we can narrow down later
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
